security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity:
                class: AppBundle:User

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: true
            provider: database_users
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout_on_user_change: true
            logout:
                path: logout
                target: homepage
            remember_me:
                secret:   '%secret%'

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
