# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.file_upload_listener:
        class: AppBundle\Doctrine\FileUploadListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    trick_voter:
        class: AppBundle\Security\TrickVoter
        autowire: true
        tags:
            - { name: security.voter }

    AppBundle\Service\FileUploader:
        arguments:
            $targetDir: '%uploads_directory%'
